#!/usr/bin/env python3

from PIL import Image
import os
import sys

im = Image("example.jpg")
im.rotate(90).resize((128,128)).save("rotated_and_resized.jpg")

for infile in sys.argv[1:]:
    f, e = os.path.splitext(infile)
    outfile = f + ".jpg"
    if infile != outfile:
        try:
            with Image.open(infile) as im:
                im.save(outfile)
        except OSError:
            print("cannot convert", infile)
